# Generated by Django 5.0.3 on 2024-03-31 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_for_cooking',
            new_name='Время_приготовления',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='Название',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='Описание',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='photo',
            new_name='Фото',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='steps_cooking',
            new_name='Шаги_приготовления',
        ),
    ]
