# Generated by Django 5.0.3 on 2024-03-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0003_rename_фото_recipe_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Описание',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Шаги_приготовления',
            new_name='steps_cooking',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Время_приготовления',
            new_name='time_for_cooking',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Название',
            new_name='title',
        ),
    ]
